# Generated by Django 5.0.7 on 2024-07-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_volume',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_volume',
            field=models.IntegerField(),
        ),
    ]
