# Generated by Django 5.0.7 on 2024-07-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_orders',
            field=models.IntegerField(verbose_name='Buy Orders'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.FloatField(verbose_name='Buy Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_volume',
            field=models.IntegerField(verbose_name='Buy Volume'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_orders',
            field=models.IntegerField(verbose_name='Sell Orders'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.FloatField(verbose_name='Sell Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_volume',
            field=models.IntegerField(verbose_name='Sell Volume'),
        ),
    ]
